name: forge_oss
description: "A whole new community app."
publish_to: "none"

environment: { sdk: ^3.6.1 }

dev_dependencies:
  melos: ^7.0.0-dev.7

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.6.1
      dependencies:
        cupertino_icons: ^1.0.8
      dev_dependencies:
        flutter_lints: ^5.0.0

workspace:
  - app
